executable            = TOPAZjobs_ScaleUp.sh
transfer_input_files  = runTOPAZ.sh

arguments             = 23 LOLO $(ProcId)-0
output                = condor_outputs/Dilepton_ScaleUp/topazTest.LOLO.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.LOLO.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.LOLO.$(ClusterId).log
+JobFlavour = "workday"
queue 4

arguments             = 23 LO $(ProcId)-4
output                = condor_outputs/Dilepton_ScaleUp/topazTest.LO.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.LO.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.LO.$(ClusterId).log
+JobFlavour = "workday"
queue 4

arguments             = 23 VI $(ProcId)-8
output                = condor_outputs/Dilepton_ScaleUp/topazTest.VI.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.VI.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.VI.$(ClusterId).log
+JobFlavour = "nextweek"
queue 24

arguments             = 23 RE $(ProcId)-32
output                = condor_outputs/Dilepton_ScaleUp/topazTest.RE.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.RE.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.RE.$(ClusterId).log
+JobFlavour = "nextweek"
queue 32

arguments             = 23 ID $(ProcId)-64
output                = condor_outputs/Dilepton_ScaleUp/topazTest.ID.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.ID.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.ID.$(ClusterId).log
+JobFlavour = "testmatch"
queue 16

arguments             = 23 DKVI $(ProcId)-80
output                = condor_outputs/Dilepton_ScaleUp/topazTest.DKVI.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.DKVI.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.DKVI.$(ClusterId).log
+JobFlavour = "testmatch"
queue 8

arguments             = 23 DKRE $(ProcId)-88
output                = condor_outputs/Dilepton_ScaleUp/topazTest.DKRE.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Dilepton_ScaleUp/topazTest.DKRE.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Dilepton_ScaleUp/topazTest.DKRE.$(ClusterId).log
+JobFlavour = "testmatch"
queue 16

arguments             = 24 LOLO $(ProcId)-0
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.LOLO.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.LOLO.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.LOLO.$(ClusterId).log
+JobFlavour = "workday"
queue 4

arguments             = 24 LO $(ProcId)-4
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.LO.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.LO.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.LO.$(ClusterId).log
+JobFlavour = "workday"
queue 4

arguments             = 24 VI $(ProcId)-8
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.VI.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.VI.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.VI.$(ClusterId).log
+JobFlavour = "nextweek"
queue 24

arguments             = 24 RE $(ProcId)-32
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.RE.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.RE.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.RE.$(ClusterId).log
+JobFlavour = "nextweek"
queue 32

arguments             = 24 ID $(ProcId)-64
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.ID.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.ID.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.ID.$(ClusterId).log
+JobFlavour = "testmatch"
queue 16

arguments             = 24 DKVI $(ProcId)-80
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.DKVI.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.DKVI.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.DKVI.$(ClusterId).log
+JobFlavour = "testmatch"
queue 8

arguments             = 24 DKRE $(ProcId)-88
output                = condor_outputs/Semileptonic_ScaleUp/topazTest.DKRE.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Semileptonic_ScaleUp/topazTest.DKRE.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Semileptonic_ScaleUp/topazTest.DKRE.$(ClusterId).log
+JobFlavour = "testmatch"
queue 16

arguments             = 25 LOLO $(ProcId)-0
output                = condor_outputs/Hadronic_ScaleUp/topazTest.LOLO.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.LOLO.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.LOLO.$(ClusterId).log
+JobFlavour = "workday"
queue 4

arguments             = 25 LO $(ProcId)-4
output                = condor_outputs/Hadronic_ScaleUp/topazTest.LO.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.LO.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.LO.$(ClusterId).log
+JobFlavour = "workday"
queue 4

arguments             = 25 VI $(ProcId)-8
output                = condor_outputs/Hadronic_ScaleUp/topazTest.VI.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.VI.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.VI.$(ClusterId).log
+JobFlavour = "nextweek"
queue 24

arguments             = 25 RE $(ProcId)-32
output                = condor_outputs/Hadronic_ScaleUp/topazTest.RE.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.RE.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.RE.$(ClusterId).log
+JobFlavour = "nextweek"
queue 32

arguments             = 25 ID $(ProcId)-64
output                = condor_outputs/Hadronic_ScaleUp/topazTest.ID.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.ID.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.ID.$(ClusterId).log
+JobFlavour = "testmatch"
queue 16

arguments             = 25 DKVI $(ProcId)-80
output                = condor_outputs/Hadronic_ScaleUp/topazTest.DKVI.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.DKVI.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.DKVI.$(ClusterId).log
+JobFlavour = "testmatch"
queue 8

arguments             = 25 DKRE $(ProcId)-88
output                = condor_outputs/Hadronic_ScaleUp/topazTest.DKRE.$(ClusterId).$(ProcId).out
error                 = condor_outputs/Hadronic_ScaleUp/topazTest.DKRE.$(ClusterId).$(ProcId).err
log                   = condor_outputs/Hadronic_ScaleUp/topazTest.DKRE.$(ClusterId).log
+JobFlavour = "testmatch"
queue 16

